#!/bin/bash

set -e

is_installed() {
  if [ -x "$(command -v $1)" ]
  then
    return 0
  else
    return 1
  fi
}

if ! is_installed "protoc"; then
  echo "==> Installing protoc"
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt install -y protobuf-compiler
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    brew install protobuf
  fi
fi

go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
go install github.com/envoyproxy/protoc-gen-validate@v0.6.7
